server:
  # 服务端口
  port: 9001
  tomcat:
    # Tomcat维护最大的对列数
    accept-count: 200
    # Tomcat线程池最多能起的线程数
    max-threads: 200
    # Tomcat最多能并发处理的请求（连接） /  服务器将在任何给定时间接受和处理的最大连接数
    max-connections: 1500
    # worker线程的最小数量
    min-spare-threads: 10
eureka:
  client:
    serviceUrl:
      # 指定注册中心
      defaultZone: http://localhost:10000/eureka/
#------------------- redis config Begin ---------------------
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/deng-manager?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
  redis:
    # Redis服务器地址
    host: 121.4.237.128
    # Redis服务器连接端口
    port: 9111
    # Redis服务器连接密码（默认为空）
    password:
    # Redis数据库索引（默认为0）
    timeout: 1000
    pool:
      # 连接超时时间（毫秒）当池内没有返回对象时最大等待时间
      maxWaitMillis: 300000
      # 连接池最大连接数（使用负值表示没有限制）
      maxTotal: 100
      # 空闲连接多长时间后会被收回
      minEvictableIdleTimeMillis: 300000
      # 一次最多evict的pool里的jedis实例个数
      numTestsPerEvictionRun: 5
      # 多长时间检查一次连接池中空闲的连接
      timeBetweenEvictionRunsMillis: 300000
      # 当调用borrow Object方法时，是否进行有效性检查
      testOnBorrow: true
      # 当调用return Object方法时，是否进行有效性检查
      testOnReturn: true
      # 空闲时是否进行验证，检查对象是否有效
      testWhileIdle: true
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
#------------------- redis config End ---------------------
datasource:
  druid:
    # Druid 初始化连接大小
    initialsize: 10
    # Druid 连接池最小空闲
    minidle: 10
    # Druid 连接池最大使用连接数量
    maxactive: 100